name: omar_env
channels:
  - conda-forge
  - defaults
  - sebp
dependencies:
  - python=3.7
  - sqlalchemy=1.3.20
  - gspread=3.6.0
  - conda-forge::psycopg2=2.8.6
  - pyarrow=3.0.0
  - boto3=1.16.12
  - oauth2client=4.1.3
  - s3fs=0.6.0 
  - pytest=6.2.2
  - pydantic=1.8.1
  - mlflow=1.22.0
  - xlrd=2.0.1
  - pandas=1.2.4
  - pip
  - wtforms==2.3.3
  - pip:
    - scikit-fda==0.5
    - tabpy==2.3.1
    - gunicorn==19.5
    - pandas-redshift==2.0.5
    - multipledispatch
    - apache-airflow==2.0.1
    - scikit-survival==0.16.0
    - fdasrsf
    - Flask-Mail
    - pytest-html